<?php echo $this->partial_header; ?>

<form class="ui fluid form segment transition<?php echo !$this->hasFilter ? " hidden" : "" ?>" id="table_filter" method="post">
    <div class="two fields">
        <div class="field">
            <label for="extension_name">Nome</label>
            <input id="extension_name" name="extension_name" value="<?php echo $this->params["extension_name"]?>" placeholder="Nome do ramal" type="text">
        </div>

        <div class="field">
            <label for="extension_number">Número</label>
            <input id="extension_number" name="extension_number" value="<?php echo $this->params["extension_number"]?>" placeholder="Número do ramal" type="text">
        </div>
    </div>

    <div class="two fields">
        <div class="field">
            <label for="extension_server">Servidor</label>
            <div class="ui selection fluid dropdown">
                <input type="hidden" name="extension_server" id="extension_server" value="<?php echo (int) $this->params["extension_server"] == 0 ? "selecione" : $this->params["extension_server"] ?>">
                <div class="text"></div>
                <i class="dropdown icon"></i>
                <div class="menu ui transition hidden">
                    <div class="item" data-value="selecione">Selecione</div>
                    <?php foreach($this->servers as $server) { ?>
                    <div class="item" data-value="<?php echo $server['server_id'] ?>"><?php echo $server['server_hostname'] ?></div>
                    <?php } ?>
                </div>
            </div>
        </div>

        <div class="field">
            <label for="extension_user">Usuário</label>
            <div class="ui selection fluid dropdown">
                <input type="hidden" name="extension_user" id="extension_user" value="<?php echo (int) $this->params["extension_user"] == 0 ? "selecione" : $this->params["extension_user"] ?>">
                <div class="text"></div>
                <i class="dropdown icon"></i>
                <div class="menu ui transition hidden">
                    <div class="item" data-value="selecione">Selecione</div>
                    <?php foreach($this->users as $user) { ?>
                    <div class="item" data-value="<?php echo $user['user_id'] ?>"><?php echo $user['user_name'] ?></div>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
    <div class="ui green labeled icon button submit">
        <i class="filter icon"></i> Filtrar
    </div>
    <a href="<?php echo $this->actions['index'] ?>" class="ui red labeled icon button">
        <i class="trash icon"></i> Limpar
    </a>
</form>

<a href="<?php echo $this->actions['add'] ?>" class="ui orange labeled icon button">
    <i class="add icon"></i> Novo ramal
</a>

<div class="ui orange labeled icon button" data-toggle="filter" data-target="#table_filter" data-placement="slide down">
    <i class="filter icon"></i> Filtros
</div>

<table class="ui table padded segment">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Número</th>
            <th>Usuário</th>
            <th>Servidor</th>
            <th class="cell action">Ações</th>
        </tr>
    </thead>
    <tbody>
        <?php
        if(count($this->extensions) > 0) {
            foreach($this->extensions as $extension) { ?>
            <tr>
                <td><?php echo $extension['extension_name'] ?></td>
                <td><?php echo $extension['extension_number'] ?></td>
                <td><?php echo $extension['user_name'] ?></td>
                <td><?php echo $extension['server_hostname'] ?></td>
                <td class="cell action">
                    <a href="<?php echo $this->url(array('module' => $this->moduleName, 'controller' => $this->controllerName, 'action' => 'view', 'id' => $extension['extension_id']), 'view_action') ?>" class="ui icon small teal button haspopup" data-content="Visualizar">
                        <i class="forward mail icon"></i>
                    </a>
                    <a href="<?php echo $this->url(array('module' => $this->moduleName, 'controller' => $this->controllerName, 'action' => 'edit', 'id' => $extension['extension_id']), 'edit_action') ?>" class="ui icon small blue button haspopup" data-content="Editar">
                        <i class="edit icon"></i>
                    </a>
                    <a href="<?php echo $this->url(array('module' => $this->moduleName, 'controller' => $this->controllerName, 'action' => 'drop', 'id' => $extension['extension_id']), 'drop_action') ?>" class="ui icon small red button <?php echo (bool) $extension['server_is_elastix'] ? ' disabled' : '' ?> haspopup drop entry" data-content="Excluir">
                        <i class="remove icon"></i>
                    </a>
                </td>
            </tr>
            <?php }
        } else { ?>
            <tr>
                <td colspan="6" class="text center">Nenhum registro encontrado</td>
            </tr>
        <?php } ?>
    </tbody>
</table>

<?php
echo $this->paginationControl($this->extensions, 'Sliding', 'pagination.phtml', array('params' => $this->params, 'routes' => $this->routes));
echo $this->partial('modaldropentry.phtml');
?>