<?php echo $this->partial_header; ?>

<form class="ui fluid form segment transition<?php echo !$this->hasFilter ? " hidden" : "" ?>" id="table_filter" method="post">
    <div class="two fields">
        <div class="field">
            <label for="user_name">Nome</label>
            <input id="user_name" name="user_name" value="<?php echo isset($this->params["user_name"]) ? $this->params["user_name"] : "" ?>" placeholder="Nome do usuário" type="text">
        </div>
        <div class="field">
            <label for="user_email">Email</label>
            <input id="user_email" name="user_email" value="<?php echo isset($this->params["user_email"]) ? $this->params["user_email"] : "" ?>" placeholder="Email de contato do usuário" type="text">
        </div>
    </div>

    <div class="two fields">
        <div class="field">
            <label for="user_login">Login</label>
            <input id="user_login" name="user_login" value="<?php echo isset($this->params["user_login"]) ? $this->params["user_login"] : "" ?>" placeholder="Login de acesso do usuário" type="text">
        </div>
        <div class="field">
            <label for="user_role">Cargo</label>
            <div class="ui selection dropdown">
                <input type="hidden" name="user_role" id="user_role" value="<?php echo isset($this->params["user_role"]) ? $this->params["user_role"] : "selecione" ?>">
                <div class="text"></div>
                <i class="dropdown icon"></i>
                <div class="menu ui transition hidden">
                    <div class="item" data-value="selecione">Selecione</div>
                    <?php foreach($this->roles as $role) { ?> 
                    <div class="item" data-value="<?php echo $role['role_id'] ?>"><?php echo $role['role_name'] ?></div>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>

    <div class="ui green labeled icon button submit">
        <i class="filter icon"></i> Filtrar
    </div>
    <a href="<?php echo $this->actions['index'] ?>" class="ui red labeled icon button">
        <i class="trash icon"></i> Limpar
    </a>
</form>

<a href="<?php echo $this->actions['add'] ?>" class="ui orange labeled icon button">
    <i class="add icon"></i> Novo usuário
</a>

<div class="ui orange labeled icon button" data-toggle="filter" data-target="#table_filter" data-placement="slide down">
    <i class="filter icon"></i> Filtros
</div>

<table class="ui table padded segment">
    <thead>
        <tr>
            <th style="width: 20%">Nome</th>
            <th style="width: 20%">Email</th>
            <th style="width: 15%">Login</th>
            <th style="width: 15%">Cargo</th>
            <th class="cell action">Ações</th>
        </tr>
    </thead>
    <tbody>
        <?php 
        if(count($this->users) > 0) {
        foreach($this->users as $user) { ?>
        <tr>
            <td><?php echo $user['user_name'] ?></td>
            <td><?php echo $user['user_email'] ?></td>
            <td><?php echo $user['user_login'] ?></td>
            <td><?php echo $user['role_name'] ?></td>
            <td class="cell action">
                <a href="<?php echo $this->url(array('module' => $this->moduleName, 'controller' => $this->controllerName, 'action' => 'view', 'id' => $user['user_id']), $this->routes['view']) ?>" class="ui icon small teal button haspopup" data-content="Visualizar">
                    <i class="forward mail icon"></i>
                </a>
                <a href="<?php echo $this->url(array('module' => $this->moduleName, 'controller' => $this->controllerName, 'action' => 'edit', 'id' => $user['user_id']), $this->routes['edit']) ?>" class="ui icon small blue button haspopup" data-content="Editar">
                    <i class="edit icon"></i>
                </a>
                <a href="<?php echo $this->url(array('module' => $this->moduleName, 'controller' => $this->controllerName, 'action' => 'drop', 'id' => $user['user_id']), $this->routes['drop']) ?>" class="ui icon small red button haspopup drop entry" data-content="Excluir">
                    <i class="remove icon"></i>
                </a>
            </td>
        </tr>
        <?php }
        } else { ?>
        <tr>
            <td colspan="5" class="text center">Nenhum registro encontrado</td>
        </tr>
        <?php
        } ?>
    </tbody>
</table>

<?php
echo $this->paginationControl($this->users, 'Sliding', 'pagination.phtml', array('params' => $this->params, 'routes' => $this->routes));
echo $this->partial('modaldropentry.phtml');
?>