<div class="ui vertically divided grid">
    <div class="five column row">
        <div class="two columns">
            <div id="chart1"></div>
        </div>
        <div class="column chart description">
            <h4 class="ui header">Gráfico 1</h4>
            <p>
                Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque volutpat mattis eros. Nullam malesuada erat ut turpis. Suspendisse urna nibh, viverra non, semper suscipit, posuere a, pede.
            </p>
        </div>
    </div>
    <div class="five column row">
        <div class="two columns">
            <div id="chart2"></div>
        </div>
        <div class="column chart description">
            <h4 class="ui header">Gráfico 2</h4>
            <p>
                Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque volutpat mattis eros. Nullam malesuada erat ut turpis. Suspendisse urna nibh, viverra non, semper suscipit, posuere a, pede.
            </p>
        </div>
    </div>
    <div class="five column row">
        <div class="two columns">
            <div id="chart3"></div>
        </div>
        <div class="column chart description">
            <h4 class="ui header">Gráfico 3</h4>
            <p>
                Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque volutpat mattis eros. Nullam malesuada erat ut turpis. Suspendisse urna nibh, viverra non, semper suscipit, posuere a, pede.
            </p>
        </div>
    </div>
</div>