<?php echo $this->partial_header; ?>

<form class="ui fluid form segment transition<?php echo !$this->hasFilter ? " hidden" : "" ?>" id="table_filter" method="post">
    <div class="two fields">
        <div class="field">
            <label for="queue_name">Nome</label>
            <input id="queue_name" name="queue_name" value="<?php echo $this->params["queue_name"]?>" placeholder="Nome da fila" type="text">
        </div>

        <div class="field">
            <label for="queue_number">Número</label>
            <input id="queue_number" name="queue_number" value="<?php echo $this->params["queue_number"]?>" placeholder="Número da fila" type="text">
        </div>
    </div>

    <div class="two fields">
        <div class="field">
            <label for="queue_server">Servidor</label>
            <div class="ui selection fluid dropdown">
                <input type="hidden" name="queue_server" id="queue_server" value="<?php echo (int) $this->params["queue_server"] == 0 ? "selecione" : $this->params["queue_server"] ?>">
                <div class="text"></div>
                <i class="dropdown icon"></i>
                <div class="menu ui transition hidden ">
                    <div class="item" data-value="selecione">Selecione</div>
                    <?php foreach($this->servers as $server) { ?>
                    <div class="item" data-value="<?php echo $server['server_id'] ?>"><?php echo $server['server_hostname'] ?></div>
                    <?php } ?>
                </div>
            </div>
        </div>

        <div class="field">
            <label for="queue_company">Empresa</label>
            <div class="ui selection fluid dropdown">
                <input type="hidden" name="queue_company" id="queue_company" value="<?php echo (int) $this->params["queue_company"] == 0 ? "selecione" : $this->params["queue_company"] ?>">
                <div class="text"></div>
                <i class="dropdown icon"></i>
                <div class="menu ui transition hidden">
                    <div class="item" data-value="selecione">Selecione</div>
                    <?php foreach($this->companies as $company) { ?>
                    <div class="item" data-value="<?php echo $company['company_id'] ?>"><?php echo $company['company_name'] ?></div>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
    <div class="ui green labeled icon button submit">
        <i class="filter icon"></i> Filtrar
    </div>
    <a href="<?php echo $this->actions['index'] ?>" class="ui red labeled icon button">
        <i class="trash icon"></i> Limpar
    </a>
</form>

<a href="<?php echo $this->actions['add'] ?>" class="ui orange labeled icon button">
    <i class="add icon"></i> Nova fila
</a>

<div class="ui orange labeled icon button" data-toggle="filter" data-target="#table_filter" data-placement="slide down">
    <i class="filter icon"></i> Filtros
</div>

<table class="ui table padded segment">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Número</th>
            <th>Empresa</th>
            <th>Servidor</th>
            <th class="cell action">Ações</th>
        </tr>
    </thead>
    <tbody>
        <?php
        if(count($this->queues) > 0) {
            foreach($this->queues as $queue) { ?>
            <tr>
                <td><?php echo $queue['queue_name'] ?></td>
                <td><?php echo $queue['queue_number'] ?></td>
                <td><?php echo $queue['company_name'] ?></td>
                <td><?php echo $queue['server_hostname'] ?></td>
                <td class="cell action">
                    <a href="<?php echo $this->url(array('module' => $this->moduleName, 'controller' => $this->controllerName, 'action' => 'view', 'id' => $queue['queue_id']), 'view_action') ?>" class="ui icon small teal button haspopup" data-content="Visualizar">
                        <i class="forward mail icon"></i>
                    </a>
                    <a href="<?php echo $this->url(array('module' => $this->moduleName, 'controller' => $this->controllerName, 'action' => 'edit', 'id' => $queue['queue_id']), 'edit_action') ?>" class="ui icon small blue button haspopup" data-content="Editar">
                        <i class="edit icon"></i>
                    </a>
                    <a href="<?php echo $this->url(array('module' => $this->moduleName, 'controller' => $this->controllerName, 'action' => 'drop', 'id' => $queue['queue_id']), 'drop_action') ?>" class="ui icon small red button <?php echo (bool) $queue['server_is_elastix'] ? ' disabled' : '' ?> haspopup drop entry" data-content="Excluir">
                        <i class="remove icon"></i>
                    </a>
                </td>
            </tr>
            <?php }
        } else { ?>
            <tr>
                <td colspan="5" class="text center">Nenhum registro encontrado</td>
            </tr>
        <?php } ?>
    </tbody>
</table>

<?php
echo $this->paginationControl($this->queues, 'Sliding', 'pagination.phtml', array('params' => $this->params, 'routes' => $this->routes));
echo $this->partial('modaldropentry.phtml');
?>