<?php echo $this->doctype() ?>
<html>
<head>
    <?php echo $this->headTitle() . PHP_EOL ?>
    <!-- Exibindo as meta tags -->
    <?php echo $this->headMeta() . PHP_EOL ?>
    <base href="<?php echo $this->baseUrl('/'); ?>">
    <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700|Open+Sans:300italic,400,300,700' rel='stylesheet' type='text/css'>
    <?php echo $this->headLink() . PHP_EOL ?>
</head>
<body class="ui transition hidden">
    <?php echo $this->partial_navigation ?>
    <div id="app_wrapper" class="ui grid">
        <div class="row">
            <div class="column">
                <?php echo $this->layout()->content; ?>
            </div>
        </div>
    </div>
    <?php echo $this->partial_sidebar ?>
    <?php echo $this->headScript(); ?>
</body>
</html>
