<?php echo $this->partial_header; ?>

<form class="ui fluid form segment transition<?php echo !$this->hasFilter ? " hidden" : "" ?>" id="table_filter" method="post">
    <div class="field">
        <label for="group_name">Nome</label>
        <input id="group_name" name="group_name" value="<?php echo isset($this->params["group_name"]) ? $this->params["group_name"] : "" ?>" placeholder="Nome da empresa" type="text">
    </div>

    <div class="ui green labeled icon button submit">
        <i class="filter icon"></i> Filtrar
    </div>
    <a href="<?php echo $this->actions['index'] ?>" class="ui red labeled icon button">
        <i class="trash icon"></i> Limpar
    </a>
</form>

<a href="<?php echo $this->actions['add'] ?>" class="ui orange labeled icon button">
    <i class="add icon"></i> Novo grupo
</a>

<div class="ui orange labeled icon button" data-toggle="filter" data-target="#table_filter" data-placement="slide down">
    <i class="filter icon"></i> Filtros
</div>

<table class="ui table padded segment">
    <thead>
        <tr>
            <th>Nome</th>
            <th class="cell action">Ações</th>
        </tr>
    </thead>
    <tbody>
        <?php 
        if(count($this->groups) > 0) {
        foreach($this->groups as $group) { ?>
        <tr>
            <td><?php echo $group['group_name'] ?></td>
            <td class="cell action">
                <a href="<?php echo $this->url(array('module' => $this->moduleName, 'controller' => $this->controllerName, 'action' => 'view', 'id' => $group['group_id']), $this->routes['view']) ?>" class="ui icon small teal button haspopup" data-content="Visualizar">
                    <i class="forward mail icon"></i>
                </a>
                <a href="<?php echo $this->url(array('module' => $this->moduleName, 'controller' => $this->controllerName, 'action' => 'edit', 'id' => $group['group_id']), $this->routes['edit']) ?>" class="ui icon small blue button haspopup" data-content="Editar">
                    <i class="edit icon"></i>
                </a>
                <a href="<?php echo $this->url(array('module' => $this->moduleName, 'controller' => $this->controllerName, 'action' => 'drop', 'id' => $group['group_id']), $this->routes['drop']) ?>" class="ui icon small red button haspopup drop entry" data-content="Excluir">
                    <i class="remove icon"></i>
                </a>
            </td>
        </tr>
        <?php }
        } else { ?>
        <tr>
            <td colspan="2" class="text center">Nenhum registro encontrado</td>
        </tr>
        <?php
        } ?>
    </tbody>
</table>

<?php
echo $this->paginationControl($this->groups, 'Sliding', 'pagination.phtml', array('params' => $this->params, 'routes' => $this->routes));
echo $this->partial('modaldropentry.phtml');
?>