<?php echo $this->partial('header.phtml') ?>

<form action="<?php echo $this->activeSaveAction ?>" method="post" class="ui fluid form segment">
    <?php if(!is_null($this->server)) { ?>
    <input type="hidden" id="server_id" name="server_id" value="<?php echo $this->server['server_id'] ?>">
    <?php } ?>
    <div class="two fields">
        <div class="field">
            <label for="server_hostname">Hostname</label>
            <input id="server_hostname" name="server_hostname" value="<?php echo $this->server["server_hostname"]?>" placeholder="Hostname da máquina" type="text">
        </div>
        <div class="field">
            <label for="server_ip_address">IP</label>
            <input id="server_ip_address" name="server_ip_address" value="<?php echo $this->server["server_ip_address"]?>" placeholder="Endereço de IP da interface principal" type="text">
        </div>
    </div>
    <div class="two fields">
        <div class="field">
            <label for="server_database_user">Usuário MySQL</label>
            <input id="server_database_user" name="server_database_user" value="<?php echo $this->server["server_database_user"]?>" placeholder="Usuário do banco de dados" type="text">
        </div>
        <div class="field">
            <label for="server_database_password">Senha MySQL</label>
            <input id="server_database_password" name="server_database_password" value="<?php echo $this->server["server_database_password"]?>" placeholder="Senha do banco de dados" type="password">
        </div>
    </div>
    <div class="two fields">
        <div class="field">
            <label for="server_ami_user">Usuário AMI</label>
            <input id="server_ami_user" name="server_ami_user" value="<?php echo $this->server["server_ami_user"]?>" placeholder="Usuário do Asterisk Manager Interface" type="text">
        </div>
        <div class="field">
            <label for="server_ami_secret">Senha AMI</label>
            <input id="server_ami_secret" name="server_ami_secret" value="<?php echo $this->server["server_ami_secret"]?>" placeholder="Senha do Asterisk Manager Interface" type="password">
        </div>
    </div>
    <div class="field">
        <label for="server_is_elastix">Elastix?</label>
        <div class="ui selection dropdown">
            <input type="hidden" name="server_is_elastix" id="server_is_elastix" value="<?php echo $this->server["server_is_elastix"] == 0 && !is_null($this->server['server_is_elastix']) ? "nao" : "sim" ?>">
            <div class="text"><?php echo $this->server["server_is_elastix"] == "nao" ? "Não" : "Sim" ?></div>
            <i class="dropdown icon"></i>
            <div class="menu ui transition hidden">
                <div class="item" data-value="sim">Sim</div>
                <div class="item active" data-value="nao">Não</div>
            </div>
        </div>
    </div>
    <div class="ui green labeled icon button submit">
        <i class="save icon"></i> Salvar
    </div>
    <a href="<?php echo $this->activeIndexAction ?>" class="ui red labeled icon button">
        <i class="reply mail icon"></i> Cancelar
    </a>
</form>