<?php echo $this->partial_header; ?>

<form class="ui fluid form segment transition<?php echo !$this->hasFilter ? " hidden" : "" ?>" id="table_filter" method="post">
    <div class="two fields">
        <div class="field">
            <label for="server_hostname">Hostname</label>
            <input id="server_hostname" name="server_hostname" value="<?php echo isset($this->params["server_hostname"]) ? $this->params["server_hostname"] : "" ?>" placeholder="Hostname da máquina" type="text">
        </div>
        <div class="field">
            <label for="server_ip_address">IP</label>
            <input id="server_ip_address" name="server_ip_address" value="<?php echo isset($this->params["server_ip_address"]) ? $this->params["server_ip_address"] : ""?>" placeholder="Endereço de IP da interface principal" type="text">
        </div>
    </div>
    <div class="two fields">
        <div class="field">
            <label for="server_database_user">Usuário MySQL</label>
            <input id="server_database_user" name="server_database_user" value="<?php echo isset($this->params["server_database_user"]) ? $this->params["server_database_user"] : ""?>" placeholder="Usuário do banco de dados" type="text">
        </div>
        <div class="field">
            <label for="server_ami_user">Usuário AMI</label>
            <input id="server_ami_user" name="server_ami_user" value="<?php echo isset($this->params["server_ami_user"]) ? $this->params["server_ami_user"] : ""?>" placeholder="Usuário do Asterisk Manager Interface" type="text">
        </div>
    </div>
    <div class="field">
        <label for="server_is_elastix">Elastix?</label>
        <div class="ui selection dropdown">
            <input type="hidden" name="server_is_elastix" id="server_is_elastix" value="<?php echo isset($this->params["server_is_elastix"]) ? $this->params["server_is_elastix"] : "selecione" ?>">
            <div class="text"></div>
            <i class="dropdown icon"></i>
            <div class="menu ui transition hidden">
                <div class="item" data-value="selecione">Selecione</div>
                <div class="item" data-value="sim">Sim</div>
                <div class="item active" data-value="nao">Não</div>
            </div>
        </div>
    </div>
    <div class="ui green labeled icon button submit">
        <i class="filter icon"></i> Filtrar
    </div>
    <a href="<?php echo $this->actions['index'] ?>" class="ui red labeled icon button">
        <i class="trash icon"></i> Limpar
    </a>
</form>

<a href="<?php echo $this->actions['add'] ?>" class="ui orange labeled icon button">
    <i class="add icon"></i> Novo servidor
</a>

<div class="ui orange labeled icon button" data-toggle="filter" data-target="#table_filter" data-placement="slide down">
    <i class="filter icon"></i> Filtros
</div>

<table class="ui table padded segment">
    <thead>
        <tr>
            <th>Hostname</th>
            <th>IP</th>
            <th>Usuário MySQL</th>
            <th>Usuário AMI</th>
            <th>Elastix?</th>
            <th class="cell action">Ações</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->servers as $server) { ?>
        <tr>
            <td><?php echo $server['server_hostname'] ?></td>
            <td><?php echo $server['server_ip_address'] ?></td>
            <td><?php echo $server['server_database_user'] ?></td>
            <td><?php echo $server['server_ami_user'] ?></td>
            <td><?php echo $server['server_is_elastix'] == 0 ? "Não" : "Sim" ?></td>
            <td class="cell action">
                <a href="<?php echo $this->url(array('module' => $this->moduleName, 'controller' => $this->controllerName, 'action' => 'view', 'id' => $server['server_id']), 'view_action') ?>" class="ui icon small teal button haspopup" data-content="Visualizar">
                    <i class="forward mail icon"></i>
                </a>
                <a href="<?php echo $this->url(array('module' => $this->moduleName, 'controller' => $this->controllerName, 'action' => 'edit', 'id' => $server['server_id']), 'edit_action') ?>" class="ui icon small blue button haspopup" data-content="Editar">
                    <i class="edit icon"></i>
                </a>
                <a href="<?php echo $this->url(array('module' => $this->moduleName, 'controller' => $this->controllerName, 'action' => 'drop', 'id' => $server['server_id']), 'drop_action') ?>" class="ui icon small red button haspopup drop entry" data-content="Excluir">
                    <i class="remove icon"></i>
                </a>
            </td>
        </tr>
        <?php } ?>
    </tbody>
</table>

<?php
echo $this->paginationControl($this->servers, 'Sliding', 'pagination.phtml', array('params' => $this->params, 'routes' => $this->routes));
echo $this->partial('modaldropentry.phtml');
?>