<div class="ui small modal" id="modal_drop_entry">
    <i class="close icon"></i>
    <div class="header">
        Excluir registro
    </div>
    <div class="content">
        <div class="left">
            Têm certeza que deseja excluir o registro selecionado?
        </div>
    </div>
    <div class="actions">
        <div class="ui button red cancel">Cancelar</div>
        <div class="ui button green approve">OK</div>
    </div>
</div>