<div id="app_navigation" class="ui six column divided grid">
    <div class="ui menu red">
        <a href="<?php echo $this->baseUrl() ?>" class="active item red page-active">
            <i class="dashboard icon"></i> Dashboard
        </a>
        <a data-target="#sidebar_aplicacoes" data-toggle="sidebar" class="item red">
            <i class="grid layout icon"></i> Aplicações
        </a>
        <a data-target="#sidebar_configuracoes" data-toggle="sidebar" class="item red">
            <i class="settings icon"></i> Configurações
        </a>
        <div class="right menu">
            <div class="item">
                <div class="ui icon input">
                    <input type="text" placeholder="Procurar">
                    <i class="search link icon"></i>
                </div>
            </div>
            <div class="ui dropdown item">
                William Urbano <i class="icon dropdown"></i>
                <div class="menu">
                    <a class="item"><i class="user icon"></i> Meus dados</a>
                    <a class="item"><i class="off icon"></i> Logout</a>
                </div>
            </div>
        </div>
    </div>
</div>