<div id="app_navigation" class="ui six column divided grid">
    <div class="ui menu red">
        <?php foreach($this->menu as $menu) {
            if(!empty($menu['menu_data_target'])) {
                $target = ' data-target="' . $menu['menu_data_target'] . '" data-toggle="sidebar"';
            } else {
                $url = $this->url(array(
                    'module' => $menu['menu_module'],
                    'controller' => $menu['menu_controller'],
                    'action' => $menu['menu_action']
                    ), $menu['menu_route']
                );

                $target = ' href="' . $url . '"';
            }

            if(array_key_exists('menu_active', $menu)) {
                $active = "active ";
                $page_active = " page-active";
            } else {
                $active = "";
                $page_active = "";
            }
            ?>
        <a<?php echo $target ?> class="<?php echo $active ?>item red<?php echo $page_active?>">
            <i class="<?php echo $menu['menu_icon_class'] ?> icon"></i> <?php echo $menu['menu_name'] ?>
        </a>
        <?php } ?>
        <div class="right menu">
            <div class="item">
                <div class="ui icon input">
                    <input type="text" placeholder="Procurar">
                    <i class="search link icon"></i>
                </div>
            </div>
            <div class="ui dropdown item">
                William Urbano <i class="icon dropdown"></i>
                <div class="menu">
                    <a class="item"><i class="user icon"></i> Meus dados</a>
                    <a class="item"><i class="off icon"></i> Logout</a>
                </div>
            </div>
        </div>
    </div>
</div>