<?php if($this->pageCount > 0) { ?>
<div id="paginator">
    <div class="ui pagination menu">
        <?php
        if (isset($this->previous)) {
            $this->params['page'] = $this->previous;
            ?>
        <a class="icon item" href="<?php echo $this->url($this->params, 'index_action_pager') ?>">
            <i class="icon left arrow"></i>
        </a>
        <?php
        } else { ?>
        <a class="icon disabled item">
            <i class="icon left arrow"></i>
        </a>
        <?php }
        foreach ($this->pagesInRange as $page) {
            $this->params['page'] = $page;
            if ($page == $this->current) { ?>
            <a href="<?php echo $this->url($this->params, 'index_action_pager') ?>" class="active item">
                <?php echo $page ?>
            </a>
                <?php
            } else { ?>
            <a class="item" href="<?php echo $this->url($this->params, 'index_action_pager') ?>"><?php echo $page ?></a>
                <?php
            }
        }

        if (isset($this->next)) {
            $this->params['page'] = $this->next;
            ?>
        <a class="icon item" href="<?php echo $this->url($this->params, 'index_action_pager') ?>">
            <i class="icon right arrow"></i>
        </a>
        <?php } else { ?>
        <a class="icon disabled item">
            <i class="icon right arrow"></i>
        </a>
        <?php } ?>
    </div>

    <div class="ui text menu">
        <div class="item">
            <?php printf('Mostrando registros de %d à %d de %d encontrados', $this->firstItemNumber, $this->lastItemNumber, $this->totalItemCount) ?>
        </div>
    </div>
</div>
<?php } ?>