<div id="paginator">
    <div class="ui pagination menu">
        <a class="icon item">
            <i class="icon left arrow"></i>
        </a>
        <a class="active item">1</a>
        <div class="disabled item">...</div>
        <a class="item">10</a>
        <a class="item">11</a>
        <a class="item">12</a>
        <a class="icon item">
            <i class="icon right arrow"></i>
        </a>
    </div>

    <div class="ui text menu">
        <div class="item">Mostrando registros de 1 a 3 de 3 encontrados</div>
    </div>
</div>