<?php
foreach($this->menu as $menu) {
    if(!empty($menu['menu_data_target'])) {
 ?>
<div class="ui left sidebar vertical menu red" id="<?php echo str_replace('#', '', $menu['menu_data_target']) ?>">
    <div class="item header">
        <i class="<?php echo $menu['menu_icon_class'] ?> icon"></i> <?php echo $menu['menu_name'] ?>
    </div>
    <?php
    if(array_key_exists('childs', $menu)) {
        foreach($menu['childs'] as $childs1) {
            if(array_key_exists('childs', $childs1)) {
                ?>
                <div class="item<?php echo array_key_exists('menu_active', $childs1) ? " active" : "" ?>">
                    <i class="<?php echo $childs1['menu_icon_class'] ?> icon"></i> <b><?php echo $childs1['menu_name'] ?></b>
                    <div class="menu">
                        <?php foreach($childs1['childs'] as $childs2) {
                            $url = $this->url(array(
                                    'module' => $childs2['menu_module'],
                                    'controller' => $childs2['menu_controller'],
                                    'action' => $childs2['menu_action']
                                ), $childs2['menu_route']
                            );
                            ?>
                        <a href="<?php echo $url ?>" class="item<?php echo array_key_exists('menu_active', $childs2) ? " active" : "" ?>"><?php echo $childs2['menu_name'] ?></a>
                        <?php } ?>
                    </div>
                </div>
                <?php
            }
        }
    } else { ?>

    <?php } ?>
</div>
<?php 
    }
}

?>