<div class="ui left sidebar vertical menu red" id="sidebar_messages">
    <a class="item header">
        <i class="grid layout icon"></i>&nbsp;Aplicações
    </a>
    <div class="item active">
        <i class="suitcase icon"></i>&nbsp;<b>CRM</b>
        <div class="menu">
            <a class="item active">Clientes</a>
            <a class="item">Atendimentos</a>
            <a class="item">Meus agendamentos</a>
            <a class="item">Relatórios</a>
        </div>
    </div>
    <div class="item">
        <i class="phone icon"></i>&nbsp;<b>Telefonia</b>
        <div class="menu">
            <a class="item">Servidores</a>
            <a class="item">Filas e Ramais</a>
            <a class="item">Campanhas</a>
            <a class="item">Monitoramento</a>
            <a class="item">Relatório de chamadas</a>
        </div>
    </div>
    <div class="item">
        <i class="money icon"></i>&nbsp;<b>Tarifação</b>
        <div class="menu">
            <a class="item">Operadoras</a>
            <a class="item">Relatórios</a>
        </div>
    </div>
</div>

<div class="ui left sidebar vertical menu red" id="sidebar_friends">
    <a class="item header">
        <i class="user icon"></i>&nbsp; Friends
    </a>
    <a class="item">
        <i class="home icon"></i>&nbsp;Home
    </a>
    <a class="active item">
        <i class="heart icon"></i>&nbsp;Current Section
    </a>
    <a class="item">
        <i class="facebook icon"></i>&nbsp;Like us on Facebook
    </a>
    <div class="item">
        <b>More</b>
        <div class="menu">
            <a class="item">About</a>
            <a class="item">Contact Us</a>
        </div>
    </div>
</div>