<div class="ui left sidebar vertical menu red" id="sidebar_aplicacoes">
    <div class="item header">
        <i class="grid layout icon"></i> Aplicações
    </div>
    <div class="item active">
        <i class="suitcase icon"></i> <b>CRM</b>
        <div class="menu">
            <a class="item active">Clientes</a>
            <a class="item">Atendimentos</a>
            <a class="item">Meus agendamentos</a>
            <a class="item">Relatórios</a>
        </div>
    </div>
    <div class="item">
        <i class="phone icon"></i> <b>Telefonia</b>
        <div class="menu">
            <a class="item">Servidores</a>
            <a class="item">Filas e Ramais</a>
            <a class="item">Campanhas</a>
            <a class="item">Monitoramento</a>
            <a class="item">Relatório de chamadas</a>
        </div>
    </div>
    <div class="item">
        <i class="money icon"></i> <b>Tarifação</b>
        <div class="menu">
            <a class="item">Operadoras</a>
            <a class="item">Relatórios</a>
        </div>
    </div>
</div>

<div class="ui left sidebar vertical menu red" id="sidebar_configuracoes">
    <div class="item header">
        <i class="user icon"></i> Configurações
    </div>
    <div class="item">
        <i class="building icon"></i> <b>Empresas</b>
        <div class="menu">
            <a class="item">Empresas</a>
            <a class="item">Grupos</a>
            <a class="item">Usuários</a>
        </div>
    </div>
    <div class="item">
        <i class="reorder icon"></i> <b>Menus</b>
        <div class="menu">
            <a class="item">Menus</a>
            <a class="item">Acessos</a>
        </div>
    </div>
</div>