<?php echo $this->partial_header ?>

<form action="<?php echo $this->actions['save'] ?>" method="post" class="ui fluid form segment">
    <?php if(!is_null($this->role)) { ?>
    <input type="hidden" id="role_id" name="role_id" value="<?php echo $this->role['role_id'] ?>">
    <?php } ?>
    <div class="field">
        <label for="role_name">Nome</label>
        <input id="role_name" name="role_name" value="<?php echo $this->role["role_name"]?>" placeholder="Nome da empresa" type="text">
    </div>

    
    <div class="ui green labeled icon button submit">
        <i class="save icon"></i> Salvar
    </div>
    <a href="<?php echo $this->actions['index'] ?>" class="ui red labeled icon button">
        <i class="reply mail icon"></i> Cancelar
    </a>
</form>