<?php echo $this->partial_header ?>

<form action="<?php echo $this->actions['save'] ?>" method="post" class="ui fluid form segment">
    <?php if(!is_null($this->menu)) { ?>
    <input type="hidden" id="menu_id" name="menu_id" value="<?php echo $this->menu['menu_id'] ?>">
    <?php } ?>
    <div class="two fields">
        <div class="field">
            <label for="menu_name">Nome</label>
            <input id="menu_name" name="menu_name" value="<?php echo $this->menu["menu_name"]?>" placeholder="Nome do menu" type="text">
        </div>
        <div class="field">
            <label for="menu_page_title">Título da página</label>
            <input id="menu_page_title" name="menu_page_title" value="<?php echo $this->menu["menu_page_title"]?>" placeholder="Título para ser exibido quando for a página ativa" type="text">
        </div>
    </div>
    <div class="field">
        <label for="menu_description">Descrição</label>
        <input id="menu_description" name="menu_description" value="<?php echo $this->menu["menu_description"]?>" placeholder="Breve descrição do menu" type="text">
    </div>
    <div class="two fields">
        <div class="field">
            <label for="menu_module">Módulo</label>
            <input id="menu_module" name="menu_module" value="<?php echo $this->menu["menu_module"]?>" placeholder="Nome do módulo do Zend Framework" type="text">
        </div>
        <div class="field">
            <label for="menu_controller">Controladora</label>
            <input id="menu_controller" name="menu_controller" value="<?php echo $this->menu["menu_controller"]?>" placeholder="Nome da controladora do Zend Framework" type="text">
        </div>
    </div>
    <div class="two fields">
        <div class="field">
            <label for="menu_action">Ação</label>
            <input id="menu_action" name="menu_action" value="<?php echo $this->menu["menu_action"]?>" placeholder="Nome da ação do Zend Framework" type="text">
        </div>
        <div class="field">
            <label for="menu_route">Rota</label>
            <input id="menu_route" name="menu_route" value="<?php echo $this->menu["menu_route"]?>" placeholder="Nome da rota URL do Zend Framework" type="text">
        </div>
    </div>
    <div class="two fields">
        <div class="field">
            <label for="menu_data_target">Elemento alvo</label>
            <input id="menu_data_target" name="menu_data_target" value="<?php echo $this->menu["menu_data_target"]?>" placeholder="Seletor jQuery do elemento de destino do menu (ex: sidebars)" type="text">
        </div>
        <div class="field">
            <label for="menu_icon_class">Ícone</label>
            <input id="menu_icon_class" name="menu_icon_class" value="<?php echo $this->menu["menu_icon_class"]?>" placeholder="Classe do ícone que representa o menu" type="text">
        </div>
    </div>
    <div class="two fields">
        <div class="field">
            <label for="menu_parent">Menu superior</label>
            <div class="ui selection fluid dropdown">
                <input type="hidden" name="menu_parent" id="menu_parent" value="<?php echo isset($this->menu["menu_parent"]) ? $this->menu["menu_parent"] : "selecione" ?>">
                <div class="text"></div>
                <i class="dropdown icon"></i>
                <div class="menu ui transition hidden">
                    <div class="item" data-value="selecione">Selecione</div>
                    <?php foreach($this->menus as $k => $v) { ?> 
                    <div class="item" data-value="<?php echo $k ?>"><?php echo $v ?></div>
                    <?php } ?>
                </div>
            </div>
        </div>
        <div class="field">
            <label for="menu_order">Ordem</label>
            <div class="ui selection fluid dropdown">
                <input type="hidden" name="menu_order" id="menu_order" value="<?php echo isset($this->menu["menu_order"]) ? $this->menu["menu_order"] : "selecione" ?>">
                <div class="text"></div>
                <i class="dropdown icon"></i>
                <div class="menu ui transition hidden">
                    <div class="item" data-value="selecione">Selecione</div>
                    <?php for($i = 1; $i <= 50; $i++) { ?> 
                    <div class="item" data-value="<?php echo $i ?>"><?php printf('%dº', $i) ?></div>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
    
    <div class="ui divider"></div>
    
    <div class="ui green labeled icon button submit">
        <i class="save icon"></i> Salvar
    </div>
    <a href="<?php echo $this->actions['index'] ?>" class="ui red labeled icon button">
        <i class="reply mail icon"></i> Cancelar
    </a>
</form>